/* Learn only (project 6.3). The milestones that lean on a project of your own
   get a stand-in here: a small real codebase to read instead. OPE picks these
   only in Learn only; in Learning while building your own project is used. */
window.OPEBank.push(

{id: 'elite-system-course', skill: 'elite-system', solo: true, kind: 'explain', title: 'Explain a whole system',
 ask: 'This is a small booking app in three files. Explain it as if to a new engineer on their first day: what each file is for, what happens from the moment somebody books until they see it confirmed, where the data lives and what it looks like, what happens when two people want the same time, and the one part you would rewrite first and why.',
 files: {
  'store.js': "// everything the app remembers, in one file\nconst bookings = [];\nlet nextId = 1;\n\nfunction add(name, startISO) {\n  const booking = { id: nextId++, name, startISO, status: 'held' };\n  bookings.push(booking);\n  return booking;\n}\n\nfunction taken(startISO) {\n  return bookings.some((b) => b.startISO === startISO && b.status !== 'cancelled');\n}\n\nfunction list() {\n  return bookings.slice();\n}\n\nmodule.exports = { add, taken, list };\n",
  'book.js': "// the rules: what is allowed to become a booking\nconst store = require('./store.js');\n\nconst OPENS = 9, CLOSES = 17;\n\nfunction book(name, startISO) {\n  if (!name) throw new Error('We need a name.');\n  const when = new Date(startISO);\n  if (isNaN(when)) throw new Error('That is not a time.');\n  if (when.getHours() < OPENS || when.getHours() >= CLOSES) throw new Error('We are closed then.');\n  if (store.taken(startISO)) throw new Error('That time is gone.');\n  return store.add(name, startISO);\n}\n\nmodule.exports = { book };\n",
  'server.js': "// the front door: turns a web request into a booking and back into words\nconst http = require('http');\nconst { book } = require('./book.js');\nconst store = require('./store.js');\n\nhttp.createServer((req, res) => {\n  if (req.method === 'POST' && req.url === '/book') {\n    let body = '';\n    req.on('data', (c) => { body += c; });\n    req.on('end', () => {\n      try {\n        const { name, start } = JSON.parse(body);\n        const made = book(name, start);\n        res.writeHead(200, { 'content-type': 'application/json' });\n        res.end(JSON.stringify(made));\n      } catch (e) {\n        res.writeHead(400, { 'content-type': 'application/json' });\n        res.end(JSON.stringify({ error: e.message }));\n      }\n    });\n    return;\n  }\n  if (req.url === '/bookings') {\n    res.writeHead(200, { 'content-type': 'application/json' });\n    res.end(JSON.stringify(store.list()));\n    return;\n  }\n  res.writeHead(404); res.end();\n}).listen(3000);\n"
 },
 model: 'server.js is the front door: it reads the web request, hands it to book.js and turns the answer, or the error, into JSON. book.js holds the rules: a name is needed, the time must be real, inside opening hours, and not already taken. store.js is the memory: one list of bookings in the running program, each one { id, name, startISO, status }. A booking goes POST /book, JSON parsed, rules checked, store.add, the new booking back as JSON, or a 400 with a plain message. Two people wanting the same time is the weak spot: the check and the write are two steps with nothing holding them together, so both can pass the check and both get in. The other weak spot is that everything is kept in memory, so a restart loses every booking. I would put the data in a real database first, with the time as a unique column so the database itself refuses the second booking.'}

);
