/* THE GAPS EVERY OTHER COURSE TEACHES AND OPE DID NOT. Project 6.3.

   Seventeen milestones added to the ends of Parts 0, 4, 5, 6 and 7, from
   comparing this course against CS50, The Odin Project, freeCodeCamp, Full
   Stack Open and Boot.dev:

     git with other people, the things CS50 spends its hardest weeks on
     (recursion, a list you build yourself, a hash table, what code costs as
     the data grows), the tools for finding a bug, how a request and a database
     really work, who somebody is, and the parts of a job nobody teaches:
     reading a codebase you did not write, dependencies, shipping and taking it
     back, and refusing bad input.

   Same shape as the rest of the bank: a check task runs its test, an explain
   task is graded by your own AI coder. */
window.OPEBank.push(

/* ============================================================ 0 Computer, git with other people */
{id: 'git-branch', skill: 'git-branch', kind: 'check', title: 'Work on a branch',
 ask: 'A branch is a copy of the project where you can work without touching the main one. In the terminal, inside your OPE Course folder: git checkout -b try-it makes one and moves you onto it. Change the words in idea.txt, then save a checkpoint whose message starts with branch. Stay on the branch, do not merge it yet.',
 files: {'idea.txt': 'Change these words on a branch.\n'},
 test: "const rel = path.relative(root, path.join(here, 'idea.txt'));\ncheck('a branch called try-it exists', () => {\n  assert.ok(/(^|\\s)try-it(\\s|$)/m.test(sh('git branch --list try-it')), 'there is no branch called try-it yet');\n});\ncheck('a checkpoint starting with branch changed idea.txt', () => {\n  const out = sh('git log -n 30 --format=%s -- \"' + rel + '\"');\n  assert.ok(/^branch/m.test(out), 'no checkpoint starting with branch has saved idea.txt');\n});\ncheck('idea.txt no longer says what it started with', () => {\n  assert.ok(!/^Change these words on a branch/.test(fs.readFileSync(path.join(here, 'idea.txt'), 'utf8')), 'idea.txt is unchanged');\n});",
 solve: {files: {'idea.txt': 'My own idea, written on a branch.\n'}, commit: 'branch: my first branch'}},

{id: 'git-conflict', skill: 'git-conflict', kind: 'check', title: 'Two changes to the same line',
 ask: 'A conflict is git refusing to guess. Make a branch, change the one line in menu.txt to something, save a checkpoint. Go back to your main branch (git checkout main, or master), change the same line to something else, save a checkpoint. Now merge the branch in: git merge <branch>. Git stops and writes <<<<<<< and >>>>>>> into the file. Pick the line you want, delete the markers and the other version, save, git add menu.txt, then git commit. The file must end up with one line and no markers.',
 files: {'menu.txt': 'Tea\n'},
 test: "const f = path.join(here, 'menu.txt');\nconst txt = fs.readFileSync(f, 'utf8');\ncheck('no conflict markers are left in menu.txt', () => {\n  assert.ok(!/<<<<<<<|=======|>>>>>>>/.test(txt), 'menu.txt still has the markers git wrote');\n});\ncheck('menu.txt says one thing, not two', () => {\n  assert.strictEqual(txt.trim().split(/\\n+/).length, 1, 'menu.txt should end up with one line');\n  assert.ok(txt.trim() !== 'Tea', 'menu.txt still says what it started with');\n});\ncheck('a merge really happened', () => {\n  const out = sh('git log -n 40 --format=%P');\n  assert.ok(out.split('\\n').some(l => l.trim().split(/\\s+/).length > 1), 'no merge checkpoint yet: a merge has two parents');\n});"},

{id: 'git-pr', skill: 'git-pr', kind: 'explain', title: 'A pull request somebody reviews',
 ask: 'Push a branch to one of your own repositories on GitHub and open a pull request against main. Then answer here: the link to it, what the change does, what a reviewer would look at first, and what you would say in the review if somebody handed you that same pull request.',
 model: 'A good answer gives the real link, says in one line what the change does and why, names the files a reviewer should open first, and reviews it honestly: what is risky, what is untested, what would have to change before merging.'},

/* ============================================================ 4 Builder, the CS50 weeks */
{id: 'build-recursion', skill: 'build-recursion', kind: 'check', title: 'A function that calls itself',
 ask: 'Recursion is a function that solves a smaller version of its own problem until there is nothing left to solve. In solution.cjs, write and export two of them, and do it without for, while or .forEach anywhere in the file. countDown(n) gives back a list from n down to 1, so countDown(3) is [3, 2, 1] and countDown(0) is []. deepSum(list) adds every number in a list that can hold lists inside lists, so deepSum([1, [2, [3, 4]], 5]) is 15.',
 files: {'solution.cjs': "// no for, no while, no forEach in this file\nfunction countDown(n) {\n\n}\n\nfunction deepSum(list) {\n\n}\n\nmodule.exports = { countDown, deepSum };\n"},
 test: "const src = fs.readFileSync(path.join(here, 'solution.cjs'), 'utf8');\nconst { countDown, deepSum } = load('solution.cjs');\ncheck('countDown(3) is [3, 2, 1]', () => assert.deepStrictEqual(countDown(3), [3, 2, 1]));\ncheck('countDown(0) is []', () => assert.deepStrictEqual(countDown(0), []));\ncheck('deepSum([1, [2, [3, 4]], 5]) is 15', () => assert.strictEqual(deepSum([1, [2, [3, 4]], 5]), 15));\ncheck('deepSum([]) is 0', () => assert.strictEqual(deepSum([]), 0));\ncheck('no loops in the file', () => {\n  assert.ok(!/\\b(for|while)\\s*\\(/.test(src), 'there is still a for or while loop');\n  assert.ok(!/\\.forEach\\s*\\(/.test(src), 'forEach is a loop too');\n});"},

{id: 'build-linked', skill: 'build-linked', kind: 'check', title: 'A list you build yourself',
 ask: 'A linked list is a chain: each link holds a value and knows the next link. No array, no [ ], no push. In solution.cjs write and export a class List with add(value) which puts a value at the end, at(i) which gives back the value at position i or undefined, size() which says how many there are, and toArray() which gives them all back in order as a real array. Only toArray may use an array.',
 files: {'solution.cjs': "class List {\n  // a link is { value, next }\n}\n\nmodule.exports = { List };\n"},
 test: "const src = fs.readFileSync(path.join(here, 'solution.cjs'), 'utf8');\nconst { List } = load('solution.cjs');\nconst l = new List();\nl.add('a'); l.add('b'); l.add('c');\ncheck('size counts the links', () => assert.strictEqual(l.size(), 3));\ncheck('at(0) is the first, at(2) is the last', () => { assert.strictEqual(l.at(0), 'a'); assert.strictEqual(l.at(2), 'c'); });\ncheck('at past the end is undefined', () => assert.strictEqual(l.at(9), undefined));\ncheck('toArray gives them back in order', () => assert.deepStrictEqual(l.toArray(), ['a', 'b', 'c']));\ncheck('an empty list has size 0', () => assert.strictEqual(new List().size(), 0));\ncheck('nothing but toArray uses an array', () => {\n  const body = src.replace(/toArray\\s*\\([^)]*\\)\\s*\\{[\\s\\S]*?\\n\\s*\\}/, '');\n  assert.ok(!/\\[\\s*\\]/.test(body) && !/\\.push\\s*\\(/.test(body) && !/new Array/.test(body), 'an array is still doing the work');\n});"},

{id: 'build-hash', skill: 'build-hash', kind: 'check', title: 'Finding something instantly',
 ask: 'A hash table turns a key into a number, and that number says which bucket to look in, so finding a key takes the same time whether you hold ten things or ten million. In solution.cjs write and export a class Table built on an array of 16 buckets. hash(key) turns a string into a number from 0 to 15. set(key, value) and get(key) use it, keys that land in the same bucket must both still work, setting the same key twice replaces the value, and get of a missing key is undefined. Do not use an object, a Map or a Set to hold the data.',
 files: {'solution.cjs': "class Table {\n  // this.buckets = new Array(16)\n}\n\nmodule.exports = { Table };\n"},
 test: "const src = fs.readFileSync(path.join(here, 'solution.cjs'), 'utf8');\nconst { Table } = load('solution.cjs');\nconst t = new Table();\ncheck('hash gives a bucket from 0 to 15', () => {\n  for (const k of ['a', 'hello', 'zzzzzz', '']) {\n    const h = t.hash(k);\n    assert.ok(Number.isInteger(h) && h >= 0 && h < 16, 'hash(' + JSON.stringify(k) + ') gave ' + h);\n  }\n});\ncheck('set then get gives the value back', () => { t.set('name', 'Kidus'); assert.strictEqual(t.get('name'), 'Kidus'); });\ncheck('a missing key is undefined', () => assert.strictEqual(t.get('nope'), undefined));\ncheck('setting the same key twice replaces it', () => { t.set('name', 'Ada'); assert.strictEqual(t.get('name'), 'Ada'); });\ncheck('two keys in the same bucket both work', () => {\n  const keys = [];\n  for (let i = 0; i < 400 && keys.length < 2; i++) { const k = 'k' + i; if (t.hash(k) === t.hash('k0')) keys.push(k); }\n  assert.strictEqual(keys.length, 2, 'could not find two keys that collide, so the test cannot prove it');\n  t.set(keys[0], 1); t.set(keys[1], 2);\n  assert.strictEqual(t.get(keys[0]), 1);\n  assert.strictEqual(t.get(keys[1]), 2);\n});\ncheck('no object, Map or Set is doing the work', () => {\n  assert.ok(!/new Map|new Set|Object\\.create|\\{\\s*\\}\\s*;/.test(src), 'something other than the buckets is holding the data');\n});"},

{id: 'build-cost', skill: 'build-cost', kind: 'check', title: 'What it costs as the data grows',
 ask: 'Two functions in slow.cjs give the same answer. One takes longer and longer as the list grows, the other barely notices. In answer.cjs export slower, the name of the slow one as text, and export faster(list), your own version of it that gives the same answer but does not get slower the same way. Then write why.md: one paragraph saying what the slow one does for every item, and what yours does instead.',
 files: {'slow.cjs': "// both find the first value that appears twice, or null\nfunction firstRepeatA(list) {\n  for (let i = 0; i < list.length; i++) {\n    for (let j = 0; j < list.length; j++) {\n      if (i !== j && list[i] === list[j]) return list[i];\n    }\n  }\n  return null;\n}\n\nfunction firstRepeatB(list) {\n  const seen = new Set();\n  for (const v of list) {\n    if (seen.has(v)) return v;\n    seen.add(v);\n  }\n  return null;\n}\n\nmodule.exports = { firstRepeatA, firstRepeatB };\n",
         'answer.cjs': "const slower = '';\n\nfunction faster(list) {\n\n}\n\nmodule.exports = { slower, faster };\n",
         'why.md': "# Why\n\n"},
 test: "const { slower, faster } = load('answer.cjs');\ncheck('you named the slow one', () => assert.strictEqual(String(slower).trim(), 'firstRepeatA'));\ncheck('faster finds the repeat', () => { assert.strictEqual(faster([3, 1, 4, 1, 5]), 1); assert.strictEqual(faster(['a', 'b', 'c']), null); });\ncheck('faster stays fast on 40,000 items', () => {\n  const big = []; for (let i = 0; i < 40000; i++) big.push(i); big.push(7);\n  const t0 = Date.now(); faster(big); const ms = Date.now() - t0;\n  assert.ok(ms < 300, 'it took ' + ms + 'ms, which means it still looks at every pair');\n});\ncheck('why.md says what changed', () => {\n  const w = fs.readFileSync(path.join(here, 'why.md'), 'utf8').replace(/^#.*$/m, '').trim();\n  assert.ok(w.length > 80, 'write a paragraph in why.md');\n});"},

/* ============================================================ 5 Debugger, the tools */
{id: 'debug-breakpoint', skill: 'debug-breakpoint', kind: 'check', title: 'Stop the program and look inside',
 ask: 'Stop guessing and look. total.cjs gives the wrong answer. Put the word debugger on its own line inside the loop, run  node inspect total.cjs  in this folder, press c to reach it, then type  repl  and look at the values of sum and line. Write what sum was on the last time round the loop into saw.txt, as a plain number. Then fix total.cjs so the test passes and take the debugger line out.',
 files: {'total.cjs': "// a cart: name, price in cents, quantity\nconst lines = [\n  { name: 'Tea', cents: 250, qty: 2 },\n  { name: 'Cake', cents: 500, qty: 1 },\n  { name: 'Coffee', cents: 300, qty: 3 }\n];\n\nfunction total(lines) {\n  let sum = 0;\n  for (const line of lines) {\n    sum += line.cents;\n  }\n  return sum;\n}\n\nconsole.log(total(lines));\nmodule.exports = { total, lines };\n",
         'saw.txt': ''},
 test: "const src = fs.readFileSync(path.join(here, 'total.cjs'), 'utf8');\nconst { total, lines } = load('total.cjs');\ncheck('total counts the quantity too', () => assert.strictEqual(total(lines), 1900));\ncheck('it still works on an empty cart', () => assert.strictEqual(total([]), 0));\ncheck('saw.txt holds the sum you saw on the last time round the old loop', () => {\n  const n = Number(String(fs.readFileSync(path.join(here, 'saw.txt'), 'utf8')).replace(/[^0-9.-]/g, ''));\n  assert.strictEqual(n, 1050, 'look again: the old loop added 250, then 500, then 300');\n});\ncheck('the debugger line is out', () => assert.ok(!/^\\s*debugger\\s*;?\\s*$/m.test(src), 'take the debugger line out before you ship'));"},

{id: 'debug-logs', skill: 'debug-logs', kind: 'check', title: 'Find the failure in the logs',
 ask: 'A real outage is found in a log file, not in an error on your screen. server.log holds one hour of requests. Find the one request that failed with a 500, and write two lines into answer.txt: first line the request id, second line the path it was asking for. Do it with your eyes or with grep, either is fine.',
 files: {'server.log': "12:00:03 req_8a1 GET /health 200 4ms\n12:00:19 req_8a2 GET /shop/mussie 200 61ms\n12:01:44 req_8a3 POST /api/book 201 130ms\n12:02:02 req_8a4 GET /shop/mussie 200 58ms\n12:03:31 req_8a5 GET /assets/logo.png 304 2ms\n12:04:57 req_8a6 POST /api/book 409 44ms  that time has just gone\n12:06:12 req_8a7 GET /api/day?slug=mussie 200 77ms\n12:07:40 req_8a8 POST /api/deposit 500 2104ms  stripe timeout\n12:08:01 req_8a9 GET /shop/mussie 200 55ms\n12:09:26 req_8b0 POST /api/book 201 118ms\n12:11:09 req_8b1 GET /health 200 3ms\n",
         'answer.txt': ''},
 test: "const a = fs.readFileSync(path.join(here, 'answer.txt'), 'utf8').trim().split(/\\n+/).map(s => s.trim());\ncheck('first line is the failing request id', () => assert.strictEqual(a[0], 'req_8a8'));\ncheck('second line is the path it asked for', () => assert.strictEqual(a[1], '/api/deposit'));"},

/* ============================================================ 6 Designer, how the machine really works */
{id: 'design-http', skill: 'design-http', kind: 'check', title: 'A request and what comes back',
 ask: 'Every web app is requests and answers. In api.cjs write and export handle(req) where req looks like { method, path, body }. Answer with { status, body }. GET /bookings gives 200 and a list. POST /bookings with a body holding name and time gives 201 and the booking it made. POST /bookings missing either one gives 400 and { error: "name and time are required" }. Anything else gives 404. A method nobody supports on a path that exists gives 405.',
 files: {'api.cjs': "const bookings = [];\n\nfunction handle(req) {\n\n}\n\nmodule.exports = { handle, bookings };\n"},
 test: "const { handle } = load('api.cjs');\ncheck('GET /bookings is 200 and a list', () => { const r = handle({ method: 'GET', path: '/bookings' }); assert.strictEqual(r.status, 200); assert.ok(Array.isArray(r.body)); });\ncheck('a good POST is 201 and gives the booking back', () => { const r = handle({ method: 'POST', path: '/bookings', body: { name: 'Ada', time: '11:00' } }); assert.strictEqual(r.status, 201); assert.strictEqual(r.body.name, 'Ada'); });\ncheck('a POST with no time is 400 and says why', () => { const r = handle({ method: 'POST', path: '/bookings', body: { name: 'Ada' } }); assert.strictEqual(r.status, 400); assert.strictEqual(r.body.error, 'name and time are required'); });\ncheck('an unknown path is 404', () => assert.strictEqual(handle({ method: 'GET', path: '/nope' }).status, 404));\ncheck('a method that does not belong there is 405', () => assert.strictEqual(handle({ method: 'DELETE', path: '/bookings' }).status, 405));\ncheck('the good POST was kept', () => { const r = handle({ method: 'GET', path: '/bookings' }); assert.ok(r.body.length >= 1); });"},

{id: 'design-join', skill: 'design-join', kind: 'check', title: 'Two tables that belong together',
 ask: 'Data is split into tables so nothing is written twice, and a join is how you put it back together. shops and bookings are two lists, and every booking holds a shop_id. In join.cjs write and export bookingsWithShop(shops, bookings): give back one row per booking, each { customer, time, shop }, where shop is the name from the matching shop. A booking whose shop is missing is left out. Then write index.md: say which column you would put an index on and what the database would otherwise have to do for every single booking.',
 files: {'join.cjs': "function bookingsWithShop(shops, bookings) {\n\n}\n\nmodule.exports = { bookingsWithShop };\n",
         'index.md': "# The index\n\n"},
 test: "const { bookingsWithShop } = load('join.cjs');\nconst shops = [{ id: 1, name: 'Mussie' }, { id: 2, name: 'Eighth Street' }];\nconst bookings = [{ customer: 'Ada', time: '11:00', shop_id: 2 }, { customer: 'Sam', time: '12:00', shop_id: 1 }, { customer: 'Lost', time: '13:00', shop_id: 9 }];\ncheck('every booking gets its shop name', () => {\n  const out = bookingsWithShop(shops, bookings);\n  assert.deepStrictEqual(out.find(r => r.customer === 'Ada'), { customer: 'Ada', time: '11:00', shop: 'Eighth Street' });\n  assert.deepStrictEqual(out.find(r => r.customer === 'Sam'), { customer: 'Sam', time: '12:00', shop: 'Mussie' });\n});\ncheck('a booking with no shop is left out', () => assert.strictEqual(bookingsWithShop(shops, bookings).length, 2));\ncheck('nothing breaks with no bookings', () => assert.deepStrictEqual(bookingsWithShop(shops, []), []));\ncheck('index.md names the column and says what happens without it', () => {\n  const t = fs.readFileSync(path.join(here, 'index.md'), 'utf8').toLowerCase();\n  assert.ok(/shop_id/.test(t), 'name the column you would index');\n  assert.ok(t.replace(/^#.*$/m, '').trim().length > 60, 'say what the database does without it');\n});"},

{id: 'design-transaction', skill: 'design-transaction', kind: 'check', title: 'Both halves, or neither',
 ask: 'Money moves in two steps: take it out of one place, put it into another. If the machine dies between them the money is gone, unless both steps are one transaction that either finishes or is thrown away. In bank.cjs write and export transfer(accounts, from, to, amount). accounts is an object of name to balance. It must refuse an amount that is not a positive number, refuse an account that does not exist, and refuse to take more than is there, and in every refusal nothing at all may change. Throw an Error with a plain message when you refuse.',
 files: {'bank.cjs': "function transfer(accounts, from, to, amount) {\n\n}\n\nmodule.exports = { transfer };\n"},
 test: "const { transfer } = load('bank.cjs');\ncheck('a good transfer moves the money', () => { const a = { ada: 100, sam: 20 }; transfer(a, 'ada', 'sam', 30); assert.deepStrictEqual(a, { ada: 70, sam: 50 }); });\ncheck('too little money changes nothing', () => { const a = { ada: 10, sam: 20 }; assert.throws(() => transfer(a, 'ada', 'sam', 30)); assert.deepStrictEqual(a, { ada: 10, sam: 20 }); });\ncheck('an account that does not exist changes nothing', () => { const a = { ada: 10 }; assert.throws(() => transfer(a, 'ada', 'ghost', 5)); assert.deepStrictEqual(a, { ada: 10 }); });\ncheck('a bad amount changes nothing', () => { const a = { ada: 10, sam: 1 }; assert.throws(() => transfer(a, 'ada', 'sam', -5)); assert.throws(() => transfer(a, 'ada', 'sam', 'lots')); assert.deepStrictEqual(a, { ada: 10, sam: 1 }); });"},

{id: 'design-auth', skill: 'design-auth', kind: 'check', title: 'Who someone is, and their password',
 ask: 'A password is never stored. What is stored is the result of scrambling it with a random salt, so a stolen database is not a list of logins. In auth.cjs use node\'s own crypto and export register(users, email, password) and login(users, email, password). register stores { email, salt, hash } and never the password itself. Two people with the same password must end up with different hashes. login gives back true only for the right password. Use crypto.randomBytes for the salt and crypto.scryptSync for the hash.',
 files: {'auth.cjs': "const crypto = require('crypto');\n\nfunction register(users, email, password) {\n\n}\n\nfunction login(users, email, password) {\n\n}\n\nmodule.exports = { register, login };\n"},
 test: "const { register, login } = load('auth.cjs');\nconst users = [];\nregister(users, 'a@example.com', 'correct horse');\nregister(users, 'b@example.com', 'correct horse');\ncheck('the password itself is nowhere in what is stored', () => {\n  assert.ok(!JSON.stringify(users).includes('correct horse'), 'the password is stored in the open');\n});\ncheck('each user has a salt and a hash', () => {\n  for (const u of users) { assert.ok(u.salt && String(u.salt).length >= 8, 'no salt'); assert.ok(u.hash && String(u.hash).length >= 16, 'no hash'); }\n});\ncheck('same password, different hashes', () => assert.notStrictEqual(String(users[0].hash), String(users[1].hash)));\ncheck('the right password logs in', () => assert.strictEqual(login(users, 'a@example.com', 'correct horse'), true));\ncheck('the wrong password does not', () => assert.strictEqual(login(users, 'a@example.com', 'correct hors'), false));\ncheck('an unknown email does not', () => assert.strictEqual(login(users, 'nobody@example.com', 'correct horse'), false));"},

/* ============================================================ 7 Elite, the parts of a job nobody teaches */
{id: 'elite-strange', skill: 'elite-strange', kind: 'explain', title: 'Read a codebase you have never seen',
 ask: 'Pick an open source project you have never opened, one you actually use, and clone it. Without running it, answer: where does it start, what happens from the moment a person does the main thing until they see a result, which three files matter most and why, how it is tested, and where you would put a new feature. Name real files and real functions.',
 model: 'A good answer names the entry file, follows one real path through the code in order, picks three files with a reason tied to what they do, says how the tests run, and points at the exact place a feature would go. Anything general enough to be about any project is a fail.'},

{id: 'elite-deps', skill: 'elite-deps', kind: 'check', title: 'The code you did not write',
 ask: 'Most of your app is other people\'s code. In this folder, run  npm init -y  then install one small package you have actually used, for example  npm i dayjs  . Then answer in deps.md: which package and its exact version, what a lock file is for, what the ^ in front of a version means and what it lets change without asking you, and one thing that could go wrong by trusting a package. The test checks the files and that you wrote the answer.',
 files: {'deps.md': "# Dependencies\n\n"},
 test: "check('a package.json is here', () => assert.ok(fs.existsSync(path.join(here, 'package.json')), 'run npm init -y in this folder'));\ncheck('a package is installed and locked', () => {\n  const pkg = JSON.parse(fs.readFileSync(path.join(here, 'package.json'), 'utf8'));\n  const deps = Object.keys(pkg.dependencies || {});\n  assert.ok(deps.length >= 1, 'install one package with npm i');\n  assert.ok(fs.existsSync(path.join(here, 'package-lock.json')), 'there is no package-lock.json');\n});\ncheck('deps.md answers all four', () => {\n  const t = fs.readFileSync(path.join(here, 'deps.md'), 'utf8').toLowerCase();\n  assert.ok(/lock/.test(t), 'say what the lock file is for');\n  assert.ok(/\\^|caret/.test(t), 'say what the ^ means');\n  assert.ok(t.replace(/^#.*$/m, '').trim().length > 150, 'answer all four, in your own words');\n});"},

{id: 'elite-deploy', skill: 'elite-deploy', kind: 'explain', title: 'Ship it, and take it back',
 ask: 'For a project of yours that is live, write the runbook: the exact command that ships it, where the secrets live and how they get there, how you know within a minute that it worked, how you would find out it broke, and the exact steps to put the last working version back. Then say which step would fail first if you were away and somebody else had to do it.',
 model: 'A good answer has real commands and real names, not "deploy the app". It says where env vars live, what is checked after a deploy, how a failure is noticed, and a rollback somebody else could follow. Naming the weakest step honestly is the point of the last question.'},

{id: 'elite-types', skill: 'elite-types', kind: 'check', title: 'Refuse the wrong input',
 ask: 'A function that trusts its input is a bug waiting for a user. In book.cjs write and export makeBooking(input) which takes { name, minutes, email } and gives back a booking object { name, minutes, email } with the name trimmed and the email lower case. It must throw an Error whose message names the field for: a missing or empty name, minutes that is not a whole number above 0, minutes over 480, and an email with no @ in it. Nothing else may throw.',
 files: {'book.cjs': "function makeBooking(input) {\n\n}\n\nmodule.exports = { makeBooking };\n"},
 test: "const { makeBooking } = load('book.cjs');\ncheck('a good booking comes back tidy', () => assert.deepStrictEqual(makeBooking({ name: '  Ada ', minutes: 60, email: 'ADA@Example.com' }), { name: 'Ada', minutes: 60, email: 'ada@example.com' }));\ncheck('a missing name is refused, and the message says name', () => assert.throws(() => makeBooking({ minutes: 60, email: 'a@b.com' }), /name/i));\ncheck('minutes that is not a number is refused', () => assert.throws(() => makeBooking({ name: 'Ada', minutes: '60', email: 'a@b.com' }), /minutes/i));\ncheck('half a minute and zero are refused', () => { assert.throws(() => makeBooking({ name: 'Ada', minutes: 1.5, email: 'a@b.com' })); assert.throws(() => makeBooking({ name: 'Ada', minutes: 0, email: 'a@b.com' })); });\ncheck('a whole day and more is refused', () => assert.throws(() => makeBooking({ name: 'Ada', minutes: 481, email: 'a@b.com' }), /minutes/i));\ncheck('an email with no at sign is refused', () => assert.throws(() => makeBooking({ name: 'Ada', minutes: 60, email: 'ada.example.com' }), /email/i));\ncheck('nothing at all is refused, not crashed', () => assert.throws(() => makeBooking()));"}

);
